---
directory_excludes:
  - .
  - ..
  - _header.md
  - root
  - roles
  - info
  - admin
  - jobs
  - isolation_segments
  - organization_quotas
  - packages
  - processes
  - resource_matches
  - revisions
  - security_groups
  - service_brokers
  - service_credential_bindings
  - service_instances
  - service_offerings
  - service_plan_visibility
  - service_plans
  - service_route_bindings
  - service_usage_events
  - sidecars
  - space_features
  - space_quotas
  - stacks
  - tasks
  - users
  - audit_events
  - deployments
  - droplets
  - feature_flags
  - app_features
  - app_usage_events
  - builds
  - buildpacks
  - manifests
  - environment_variable_groups
operations_excludes:
  - .
  - ..
  - _header.md
  - _share.md.erb
  - _unshare.md.erb
  - _object.md.erb
  - _permissions.md.erb
  - get_assigned_isolation_segment.md.erb
