openapi: "3.1.0"
info:
  title: "Cloud Foundry V3 API CRUD"
  description: "Cloud Foundry V3 API CRUD operations",
  version: 3.114.0
  license:
    name: MIT
  contact:
    name: API Support
    url: https://www.meltingturret.io
servers:
  - url: http://cf-mock-crud.example.com/v3
tags:
  - name: one
paths:
  one
  $ref: "./resources/one.yaml"
